### ISSUE TITLE
Heatmap annotation with motif's sequence logos

### ISSUE THREAD

**Issue by AngryMaciek** [zavolanlab/binding-scanner#26]
**Describe the solution you'd like**
I think we could try to annotate the final heatmap with the sequence logos of the motifs (additionally to the motifs names). I am not sure how well it would look and if it would be readable so maybe you could just implement an optional CLI flag for your plotting script? "If the flag with paths to the plots is provided then create an exdended heatmap, if not - just a simple one as we have it now".

If you follow this strategy then I think it would make sense to adjust the unit test so that it tests the "extended" version.

Make note that this annotation might be tricky when it comes to scaling. We would like to heatmap to look nicely regardless if it has 10 or 100 motifs... Therefore I would advise you to implement some dynamical scaling of the heigth of the plot (based on the number of motifs?) Actually, this scalling should also be there for the "basic" versions of the heatmaps as well, right?

**Describe alternatives you've considered**
I was considering if we should make another, separate pipeline step with another heatmap but ultimately - this would be more work. I believe it would be easier to just modify we files we already have.

@krish8484  - what do you think?

**This would be the last modification to the data processing for ver. 1.0.0. of the tool**

**Comment by krish8484** [comment]
Currently, in the heatmap, the rows are pretty small (because we had made the grids square). If we can make it back to normal, maybe it will look better? Let's decide after plotting.

The CLI flag idea is great.

As far as scaling is considered, I think `ggplot`  will take care of that. Maybe we can test it with a larger dataset.

Yes, I agree with modifying the current files instead of creating a new one. It will help reduce work and a separate pipeline seems superfluous.
